# Generated by Django 3.2.7 on 2021-09-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.FileField(blank=True, upload_to='path/to/img'),
        ),
    ]
