# Generated by Django 3.2.7 on 2021-09-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_remove_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='path/to/img'),
        ),
    ]
