# Generated by Django 3.2.7 on 2021-09-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20210914_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Cover Photo',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.FileField(blank=True, default='default.jpg', upload_to='path/to/img'),
        ),
    ]
