# Generated by Django 3.2.7 on 2021-09-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_post_cover_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_Pic',
            field=models.FileField(blank=True, default='default.jpg', upload_to='path/to/img'),
        ),
    ]
