# Generated by Django 3.2.7 on 2021-09-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='id',
        ),
        migrations.AddField(
            model_name='postimage',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.FileField(blank=True, default=1, upload_to=''),
        ),
    ]
