# Generated by Django 3.2.7 on 2021-09-19 20:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210916_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_Pic',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
