# Generated by Django 3.2.7 on 2021-09-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='slug',
            new_name='Slug',
        ),
    ]
