# Generated by Django 3.2.7 on 2021-09-22 16:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_slug_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='post', unique_with=('created_on',))),
        ),
    ]
